# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EntropyUT <- function(G, pro, mean, sigma, d) {
    .Call(`_ppgmmga_EntropyUT`, G, pro, mean, sigma, d)
}

EntropyVAR <- function(G, pro, mean, sigma, d) {
    .Call(`_ppgmmga_EntropyVAR`, G, pro, mean, sigma, d)
}

EntropySOTE <- function(data, G, pro, mean, sigma) {
    .Call(`_ppgmmga_EntropySOTE`, data, G, pro, mean, sigma)
}

EntropyMCapprox <- function(data, G, pro, mean, sigma) {
    .Call(`_ppgmmga_EntropyMCapprox`, data, G, pro, mean, sigma)
}

LinTransf <- function(mean, sigma, B, Z, G, d) {
    .Call(`_ppgmmga_LinTransf`, mean, sigma, B, Z, G, d)
}

EntropyGauss <- function(S, d) {
    .Call(`_ppgmmga_EntropyGauss`, S, d)
}

orth <- function(A, method = "QR") {
    .Call(`_ppgmmga_orth`, A, method)
}

encode <- function(par, p) {
    .Call(`_ppgmmga_encode`, par, p)
}

encodebasis <- function(par, d, p) {
    .Call(`_ppgmmga_encodebasis`, par, d, p)
}

